### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by elect86** [fzakaria/ascii85#3]
Hi Farid,

I ported your excellent ascii85 to kotlin [here](https://github.com/kotlin-graphics/uno-sdk/blob/master/src/main/kotlin/uno/convert/ascii85.kt)

I see you are way into several language... it's time for Kotlin! :stuck_out_tongue:

If you want I can push it and also implement gradle  :wink:

**Comment by fzakaria** [comment]
Hi!

Thanks for the kind words.
I am not very interested in migrating it to Kotlin.

If you'd like we should work on just releasing this as a JAR -- since I just made a pretty big important fix that you'd probably want in your fork for an issue that was raised (negative byte values)

**Comment by fzakaria** [comment]
@elect86 i released this as 1.1 to maven central.
I recommend you just use this jar to track fixes. 

If you want to port it all to kotlin in this repo -- feel free to send PR.

**Comment by elect86** [comment]
Hi,

ok, I'll do if it comes again on my todo list

thanks
