### ISSUE TITLE
This class do not support empty arrays

### ISSUE THREAD

**Issue by franci** [fzakaria/ascii85#6]
I doesn't support empty byte array

>      @Test
>     public void testEmpty() {
>         byte[] empty = new byte[0];
>         String encoded = Ascii85.encode(empty);
>         try 
>         {
>             byte[] actual = Ascii85.decode(encoded);
>             assertThat(actual, is(empty));
>         } 
>         catch (Exception e) 
>         {
>             e.printStackTrace();
>         }
>     }
>

**Comment by fzakaria** [comment]
Thanks will investigate.

**Comment by fzakaria** [comment]
I could make empty byte empty string... but its not really defined.
There's no "RFC" for Ascii85 --

**Comment by odisseus** [comment]
I think converting empty input into empty output makes sense for both encoding and decoding.

**Comment by fzakaria** [comment]
Contributions welcome!
