### ISSUE TITLE
Encoded string is smaller than expected and therefore allocated ByteBuffer capacity is smaller than original byte array size, causing BufferOverflowException

### ISSUE THREAD

**Issue by seab4ss** [fzakaria/ascii85#7]
Encoded a JPEG  frame represented by byte array with original length 25820 into a Ascii85 string with 32259 length.  Which supposed to be actually 32275 = 25820 * 5 / 4;  
Then try to decode that string using Ascii85.decode();  so the Allocated ByteBuffer is 25807 = 32259 * 4 / 5,  which is less than original byte array length of 25820;

java.nio.BufferOverflowException
        at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:164)
        at java.nio.ByteBuffer.put(ByteBuffer.java:642)
        Ascii85.decode(Ascii85.java:143)

So somehow encoded string turns out to be shorter than  byteArrLen * 5/4, which breaks assumption in decode and it causes the exception. 

Thanks

**Comment by fzakaria** [comment]
I believe #10 fixed this. Closing.
A new version has been released.
